feat: use PerformanceObserver for gc stats
dnlup/doc pull request #20
Opened 2020-06-29 13:03 UTC by acheronfail

Fixes #5 

This uses the `PerformanceObserver` API to measure the default duration of garbage collections.
https://github.com/nodejs/diagnostics/blob/master/documentation/memory/step3/using_gc_traces.md?rgh-link-date=2020-06-17T22%3A50%3A46Z

The subscription calculates a rolling average over the `sampleInterval`.

2020-06-29 13:53 UTC, dnlup commented
Thanks, @acheronfail , I appreciate it. Give me some time to test this, and I'll get back to you!

2020-06-29 15:58 UTC, dnlup commented on index.js
> +      }
You used [this](https://en.wikipedia.org/wiki/Moving_average#Cumulative_moving_average) approach here, I like it.

2020-06-29 16:01 UTC, dnlup commented
Could you rebase against the latest changes in `current`? There was a misconfiguration in GitHub actions that was preventing running tests on PRs :pray:

2020-06-30 06:13 UTC, acheronfail commented
I'm not sure _how_ to deterministically trigger a `WeakCB` garbage collection cycle, so I've skipped checking for it in the tests.

Seeing as though it shares the same code as the other types, I think it's (probably) fine to leave it as is.

2020-06-30 06:24 UTC, acheronfail commented
The tests run reliably on my computer (Linux), even if I run them 10 times in a row they still pass.
Not entirely sure how we can make these more reliable in CI.

2020-06-30 09:56 UTC, acheronfail commented
Okay, after running it in GitHub Actions several times in my fork, I've got it running reliably in CI. I just had to increase the duration of the garbage collection test. This way the test runs reliably since it's more likely that garbage collection occurs.

2020-07-01 06:12 UTC, dnlup commented
> I'm not sure _how_ to deterministically trigger a `WeakCB` garbage collection cycle, so I've skipped checking for it in the tests.
> 
> Seeing as though it shares the same code as the other types, I think it's (probably) fine to leave it as is.

I agree.

> ~Okay, after running it in GitHub Actions several times in my fork, I've got it running reliably in CI. I just had to increase the duration of the garbage collection test. This way the test runs reliably since it's more likely that garbage collection occurs.~
> 
> I spoke too soon, it seems it still fails intermittently. :sigh: I'm not sure writing tests for the garbage collection is going to be easy, unless we re-architect it to allow us to mock the `PerformanceObserver` and send in dummy data during a test.

The latest tests seem to fail for something unrelated. I like the refactoring you have done so far, I would like to test the `PerformanceObserver` directly without mocking. For doing what you are suggesting the only way that comes to my mind atm is monkey patching the module `perf_hooks` to return a mock  or inject the mock as a dependency. Before taking that road I would like to try a few things.

I see errors in the custom `sampleInterval` check, mostly. Maybe it is something that could be related to the gc tests, but it seems that the tests on the gc were working with or without mocking. Let me try a few things locally. Maybe just being less strict on that timeout check could work.

I agree that testing this is not easy though, I encountered similar problems with the other metrics. We are going to find a solution.

2020-07-01 06:23 UTC, dnlup commented
As a first small thing, let's put a debug message [here](https://github.com/dnlup/doc/blob/fae108f0a528015efeaf78ab42c60c247a36e0b9/test.js#L164):

```js
t.true(elapsed >= 2000 && elapsed < 2200, `elapsed: ${elapsed}`)
```

2020-07-02 02:00 UTC, acheronfail commented
> If you could just address those nits I pointed in the previous comments we can proceed with this. This would allow me to publish a pre-release. I am confident something will come up to address these issues.

Sorry, I'm not entirely sure which nits you're referring to? Do you mean monkey-patching the `perf_hooks` module so we can mock out the `PerformanceObserver` class?

2020-07-02 05:29 UTC, dnlup requested changes

2020-07-02 05:29 UTC, dnlup commented on gc.js
> +    for (const gcEntry of list.getEntriesByType('gc')) {
Here we can use `getEntries` because we subscribed to just gc events

2020-07-02 05:29 UTC, dnlup commented on gc.js
> +    this.major = [0, undefined]
Can the `average` be `0` as default?

2020-07-02 05:29 UTC, dnlup commented on gc.js
> +      if (average === undefined) {
If we set `average` to be `0` as default, we should check if `count === 0`

2020-07-02 05:30 UTC, dnlup commented
> Sorry, I'm not entirely sure which nits you're referring to? Do you mean monkey-patching the perf_hooks module so we can mock out the PerformanceObserver class?

Sorry, I didn't submit my review correctly at the beginning so I think you didn't see my comments. I have made a new one.

2020-07-02 07:02 UTC, acheronfail commented
Ah, no worries! They're all done now. :+1:

2020-07-03 05:04 UTC, dnlup approved these changes

2020-07-03 05:06 UTC, dnlup commented
Great work @acheronfail ! Thank you so much for working on this!

I'll publish a pre-release soon with this feature that you can use by using the `next` tag when installing:

```bash
$ npm i @dnlup/doc@next
```

2020-07-03 05:07 UTC, merged

2020-07-03 05:13 UTC, dnlup commented
Published in https://github.com/dnlup/doc/releases/tag/v1.2.0-0